### ISSUE TITLE
mod cash

### ISSUE THREAD

**Issue by marcoasfonseca** [joshiejack/Harvest-Moon#135]
When the carpenters finish his house the game simply stop working and give me a crash error!
Please help!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/18/17 9:46 AM
Description: Ticking entity

java.lang.IllegalAccessError: tried to access method net.minecraft.entity.EntityHanging.func_174859_a(Lnet/minecraft/util/EnumFacing;)V from class joshie.harvest.buildings.placeable.entities.PlaceablePainting
	at joshie.harvest.buildings.placeable.entities.PlaceablePainting.getEntityHanging(PlaceablePainting.java:29)
	at joshie.harvest.buildings.placeable.entities.PlaceableHanging.getEntity(PlaceableHanging.java:24)
	at joshie.harvest.buildings.placeable.entities.PlaceableEntity.place(PlaceableEntity.java:26)
	at joshie.harvest.buildings.placeable.Placeable.place(Placeable.java:48)
	at joshie.harvest.buildings.BuildingStage.build(BuildingStage.java:104)
	at joshie.harvest.npc.entity.ai.EntityAIBuild.func_75246_d(EntityAIBuild.java:88)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at joshie.harvest.buildings.placeable.entities.PlaceablePainting.getEntityHanging(PlaceablePainting.java:29)
	at joshie.harvest.buildings.placeable.entities.PlaceableHanging.getEntity(PlaceableHanging.java:24)
	at joshie.harvest.buildings.placeable.entities.PlaceableEntity.place(PlaceableEntity.java:26)
	at joshie.harvest.buildings.placeable.Placeable.place(Placeable.java:48)
	at joshie.harvest.buildings.BuildingStage.build(BuildingStage.java:104)
	at joshie.harvest.npc.entity.ai.EntityAIBuild.func_75246_d(EntityAIBuild.java:88)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: harvestfestival.builder (joshie.harvest.npc.entity.EntityNPCBuilder)
	Entity ID: 2127
	Entity Name: Yulif
	Entity's Exact location: 89840.49, 65.00, 90003.70
	Entity's Block location: World: (89840,65,90003), Chunk: (at 0,4,3 in 5615,5625; contains blocks 89840,0,90000 to 89855,255,90015), Region: (175,175; contains chunks 5600,5600 to 5631,5631, blocks 89600,0,89600 to 90111,255,90111)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Agora é que é mesmo
	All players: 1 total; [EntityPlayerMP['_ParDeus_'/1766, l='Agora é que é mesmo', x=89828.45, y=70.87, z=89997.71]]
	Chunk stats: ServerChunkCache: 523 Drop: 0
	Level seed: 8785224897154019723
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (-208,64,248), Chunk: (at 0,4,8 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13306 game time, 13306 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2059268648 bytes (1963 MB) / 3693084672 bytes (3522 MB) up to 3693084672 bytes (3522 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3584m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2077 Optifine OptiFine_1.10.2_HD_U_D6 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{12.18.1.2077} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	dmonsters{1.142} [Deadly Monsters] (1.10.2_deadly_monsters_1.142.jar) 
	UCHIJAAAA	monsteranddungeons{0.1} [Monsters and Dungeons] ([1.10.2] Monsters And Dungeons v 1.0.jar) 
	UCHIJAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJAAAA	BetterFoliage{2.1.0} [Better Foliage] (BetterFoliage-MC1.10-2.1.0.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2142} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.13} [CoroUtil Library] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJAAAA	harvestfestival{0.5.14} [Harvest Festival] (Harvest-Festival-1.10.2-0.5.14.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	itlt{0.0.9} [It's the little things] (itlt-1.10-0.0.9.jar) 
	UCHIJAAAA	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.5.4.67} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.67.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	mobends{0.22.2} [Mo'Bends] (mobends-0.22.2_for_MC-1.10.2.jar) 
	UCHIJAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tombmanygraves{1.10.2-2.1.13} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.13.jar) 
	UCHIJAAAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.212.jar) 
	UCHIJAAAA	wawla{2.3.1.212} [What Are We Looking At] (Wawla-1.10.2-2.3.1.212.jar) 
	UCHIJAAAA	zombieawareness{1.10.2-1.11.3} [Zombie Awareness] (zombieawareness-1.10.2-1.11.3.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['_ParDeus_'/1766, l='Agora é que é mesmo', x=89828.45, y=70.87, z=89997.71]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by joshiejack** [comment]
Why are you using such an old version

**Comment by marcoasfonseca** [comment]
I didn't realize that! Thanks for the help :)
