### ISSUE TITLE
1.10.2 crash report.Harvest-Festival-1.10.2-0.6.0-219.jar

### ISSUE THREAD

**Issue by Mushroom0629** [joshiejack/Harvest-Moon#203]
Time: 2/17/18 1:20 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at joshie.harvest.calendar.CalendarAPI.getWeather(CalendarAPI.java:73)
	at net.minecraft.client.renderer.EntityRenderer.func_78484_h(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:296)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1770)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at joshie.harvest.calendar.CalendarAPI.getWeather(CalendarAPI.java:73)
	at net.minecraft.client.renderer.EntityRenderer.func_78484_h(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:296)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mushroom'/2465, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (251,77,112), Chunk: (at 11,4,0 in 15,7; contains blocks 240,0,112 to 255,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Mushroom'/2465, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by GirafiStudios** [comment]
Thanks for your report!
I thought this got fixed in 0.6.0-219. I need more information on how it happened, since I can't do much with just a crash report.
