### ISSUE TITLE
[Crash] Crash when loading chunks in the world after installing  the latest version

### ISSUE THREAD

**Issue by NONO219** [joshiejack/Harvest-Moon#212]
i used to use the old version "Harvest-Festival-1.10.2-0.5.25". After i installed the latest version "Harvest-Festival-1.10.2-0.6.0-219", minecraft started to crash every time i entered the world. 

My forge version is the latest one, provided in Hello Minecraft Launcher,  12.18.3.2511，JAVA 8 is available. 

It's okay to enter main menu, and also it's okay to run successfully after creating a new world without noticing me "missing blocks". 

But once I open the old worlds, which will notice me "missing blocks", it will crash while loading the chunks,  just CRASHES and CRASHES repeatedly after i installed the new version, so i have to re-use the old version in the mod pack, which is 0.5.25. 

i think it may not be the problem of my computer or settings.

So sad i wanna enjoy the festival!

Urgent ! could someone help?

Thanks so much! It's the best mod i've ever seen and i hope it can bring me more fun

**Comment by NONO219** [comment]
Now i've tried all the versions of 0.6, none of them works. only 0.5x versions work. Could someone explain it? I may show the crash report if needed.

AND ALSO, can the author tell me what the attached "api" documents in 0.6x versions work for ?

**Comment by NONO219** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  literalascension (literalascension-1.10.2-1.0.1.1.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.6.0-219.jar)
  FMLPlugin (inventorytweaks-1.61-58.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/27/18 2:52 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=croptype, clazz=class joshie.harvest.crops.block.BlockHFCrops$CropType, values=[FRESH, WITHERED, FRESH_DOUBLE, WITHERED_DOUBLE]} as it does not exist in BlockStateContainer{block=minecraft:farmland, properties=[moisture]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at joshie.harvest.core.base.block.BlockHFEnum.getEnumFromState(BlockHFEnum.java:90)
	at joshie.harvest.crops.block.BlockHFCrops.func_176221_a(BlockHFCrops.java:357)
	at joshie.harvest.crops.block.BlockHFCrops.getPlant(BlockHFCrops.java:376)
	at net.minecraft.block.Block.canSustainPlant(Block.java:1607)
	at net.minecraft.block.BlockFarmland.func_176529_d(BlockFarmland.java:86)
	at net.minecraft.block.BlockFarmland.func_180650_b(BlockFarmland.java:62)
	at net.minecraft.block.Block.func_180645_a(Block.java:480)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at joshie.harvest.core.base.block.BlockHFEnum.getEnumFromState(BlockHFEnum.java:90)
	at joshie.harvest.crops.block.BlockHFCrops.func_176221_a(BlockHFCrops.java:357)
	at joshie.harvest.crops.block.BlockHFCrops.getPlant(BlockHFCrops.java:376)
	at net.minecraft.block.Block.canSustainPlant(Block.java:1607)
	at net.minecraft.block.BlockFarmland.func_176529_d(BlockFarmland.java:86)
	at net.minecraft.block.BlockFarmland.func_180650_b(BlockFarmland.java:62)
	at net.minecraft.block.Block.func_180645_a(Block.java:480)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: 10
	All players: 1 total; [EntityPlayerMP['NONO'/249, l='10', x=49.65, y=67.00, z=383.86]]
	Chunk stats: ServerChunkCache: 334 Drop: 0
	Level seed: 4693282423288124318
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (28,64,256), Chunk: (at 12,4,0 in 1,16; contains blocks 16,0,256 to 31,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4277470 game time, 5724905 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 198877688 bytes (189 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_E7_pre 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	continousmusic{1.0.0} [Continous Music] ([ÎÞÏÞÒôÀÖ][1.10.x]infinitemusic-1.10.2-1.0.0.jar) 
	UCHIJAAAA	ashenwheat{3.1.4.1} [Ashenwheat] (ashenwheat-1.10.2-3.1.4.1.jar) 
	UCHIJAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJAAAA	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
	UCHIJAAAA	carryon{1.1} [Carry On] (CarryOn_MC1.10.2_v1.1.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	chineseworkshop{1.1.0.0} [ChineseWorkshop] (ChineseWorkshop_1.10.2-1.1.0.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	forgelin{1.4.1} [Forgelin] (Forgelin-1.4.1.jar) 
	UCHIJAAAA	harvestfestival{0.6.0-219} [Harvest Festival] (Harvest-Festival-1.10.2-0.6.0-219.jar) 
	UCHIJAAAA	Waila{1.8.12-B26_1.10.2} [Waila] (Hwyla-1.8.12-B26_1.10.2.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.10.0} [InfinityLib] (infinitylib-0.10.0.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (inventorytweaks-1.61-58.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJAAAA	literalascension{1.10.2-1.0.1.1} [Literal Ascension] (literalascension-1.10.2-1.0.1.1.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.1-1.10.2.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.2.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	NyankoMod{1.3.0} [NyankoMod] (NyankoMod_1.10.2_1.3.0.jar) 
	UCHIJAAAA	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.6.3} [Storage Drawers] (StorageDrawers-1.10.2-3.6.3.jar) 
	UCHIJAAAA	superminer_core{2.2.32.270} [SuperMiner] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_captivator{[1.10.2]-2.2.32.270} [SuperMiner Captivator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_cropinator{[1.10.2]-2.2.32.270} [SuperMiner Copinator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_excavator{[1.10.2]-2.2.32.270} [SuperMiner Excavator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_illuminator{[1.10.2]-2.2.32.270} [SuperMiner Illuminator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_lumbinator{[1.10.2]-2.2.32.270} [SuperMiner Lumbinator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_shaftanator{[1.10.2]-2.2.32.270} [SuperMiner Shaftanator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_substitutor{[1.10.2]-2.2.32.270} [SuperMiner Substitutor] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	superminer_veinator{[1.10.2]-2.2.32.270} [SuperMiner Veinator] (superminer-[1.10.2]-2.2.32.270.jar) 
	UCHIJAAAA	expforce{3.0.1.422} [Experience Force] (TeaStory-3.0.1.504-1.10.2.zip) 
	UCHIJAAAA	teastory{3.0.1.504} [Tea: The Story] (TeaStory-3.0.1.504-1.10.2.zip) 
	UCHIJAAAA	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.3.1.2.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
literalascension (literalascension-1.10.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.4.1.jar)
  
HFTransformer (Harvest-Festival-1.10.2-0.6.0-219.jar)
  joshie.harvest.asm.HFTransformer
FMLPlugin (inventorytweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['NONO'/249, l='10', x=49.65, y=67.00, z=383.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_E7_pre
	Render Distance Chunks: 6
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13+V6+Lite.zip
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
