### ISSUE TITLE
I crashes when trying to build Townhall. I dont know how to fix it

### ISSUE THREAD

**Issue by luke82304** [joshiejack/Harvest-Moon#213]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.6.0-219.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 2018/8/1 下午 3:16
Description: Unexpected error

com.google.common.util.concurrent.UncheckedExecutionException: net.minecraft.util.ReportedException: Tesselating block model
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at joshie.harvest.buildings.render.PreviewEvent.getRenderer(PreviewEvent.java:53)
	at joshie.harvest.buildings.render.PreviewEvent.renderBuildingPreview(PreviewEvent.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_37_PreviewEvent_renderBuildingPreview_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:570)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1896)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1347)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: net.minecraft.util.ReportedException: Tesselating block model
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:66)
	at joshie.harvest.buildings.render.BuildingRenderer.addRender(BuildingRenderer.java:44)
	at joshie.harvest.buildings.render.BuildingRenderer.setupRender(BuildingRenderer.java:37)
	at joshie.harvest.buildings.render.BuildingRenderer.<init>(BuildingRenderer.java:29)
	at joshie.harvest.buildings.render.PreviewEvent.lambda$getRenderer$0(PreviewEvent.java:53)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 24 more
Caused by: java.lang.NullPointerException
	at joshie.harvest.quests.block.BlockQuestBoard.func_176221_a(BlockQuestBoard.java:77)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1376)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1343)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
	at ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1054)
	at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:773)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:539)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:107)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:142)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at joshie.harvest.buildings.render.PreviewEvent.getRenderer(PreviewEvent.java:53)
	at joshie.harvest.buildings.render.PreviewEvent.renderBuildingPreview(PreviewEvent.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_37_PreviewEvent_renderBuildingPreview_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:570)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1896)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1574)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Luke'/1030, l='MpServer', x=-114.18, y=69.93, z=105.33]]
	Chunk stats: MultiplayerChunkCache: 404, 404
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-104,64,88), Chunk: (at 8,4,8 in -7,5; contains blocks -112,0,80 to -97,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 136181 game time, 136181 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntityCreeper['苦力怕'/896, l='MpServer', x=-103.83, y=44.00, z=167.59], EntitySpider['蜘蛛'/897, l='MpServer', x=-102.00, y=48.00, z=166.46], EntityZombie['殭屍'/899, l='MpServer', x=-103.30, y=44.00, z=180.50], EntitySkeleton['骷髏'/900, l='MpServer', x=-107.78, y=43.00, z=178.50], EntitySkeleton['骷髏'/901, l='MpServer', x=-103.50, y=44.00, z=182.50], EntityPlayerSP['Luke'/1030, l='MpServer', x=-114.18, y=69.93, z=105.33], EntityBat['蝙蝠'/906, l='MpServer', x=-90.98, y=51.10, z=105.54], EntityBat['蝙蝠'/907, l='MpServer', x=-94.46, y=51.10, z=103.92], EntityBat['蝙蝠'/908, l='MpServer', x=-93.52, y=52.10, z=103.25], EntityCreeper['苦力怕'/909, l='MpServer', x=-93.66, y=50.00, z=106.23], EntityCreeper['苦力怕'/910, l='MpServer', x=-86.78, y=48.00, z=105.50], EntityZombie['殭屍'/911, l='MpServer', x=-89.13, y=49.00, z=105.50], EntitySpider['蜘蛛'/912, l='MpServer', x=-93.99, y=20.00, z=118.49], EntityEnderman['終界使者'/913, l='MpServer', x=-91.70, y=52.00, z=171.53], EntityBat['蝙蝠'/925, l='MpServer', x=-70.26, y=47.10, z=71.30], EntitySpider['蜘蛛'/926, l='MpServer', x=-76.42, y=15.00, z=109.00], EntityBat['蝙蝠'/927, l='MpServer', x=-80.00, y=16.12, z=110.97], EntityBat['蝙蝠'/928, l='MpServer', x=-74.25, y=35.35, z=95.25], EntityCreeper['苦力怕'/929, l='MpServer', x=-66.50, y=19.00, z=127.50], EntitySkeleton['骷髏'/930, l='MpServer', x=-72.50, y=19.00, z=118.37], EntitySkeleton['骷髏'/931, l='MpServer', x=-72.50, y=19.00, z=119.07], EntityChicken['雞'/804, l='MpServer', x=-193.69, y=64.00, z=179.12], EntityPig['豬'/808, l='MpServer', x=-179.30, y=67.00, z=58.49], EntityPig['豬'/809, l='MpServer', x=-178.76, y=66.00, z=52.21], EntityZombie['殭屍'/940, l='MpServer', x=-48.50, y=25.00, z=32.50], EntityZombie['殭屍'/941, l='MpServer', x=-62.50, y=41.00, z=82.50], EntityRabbit['兔子'/942, l='MpServer', x=-54.50, y=63.00, z=90.50], EntityRabbit['兔子'/943, l='MpServer', x=-55.70, y=63.00, z=88.30], EntitySheep['綿羊'/815, l='MpServer', x=-168.51, y=65.00, z=40.79], EntityWitch['女巫'/944, l='MpServer', x=-48.50, y=33.00, z=109.50], EntitySheep['綿羊'/816, l='MpServer', x=-168.87, y=66.00, z=48.34], EntityBat['蝙蝠'/945, l='MpServer', x=-49.41, y=37.73, z=93.81], EntitySheep['綿羊'/817, l='MpServer', x=-170.02, y=67.00, z=55.70], EntityRabbit['兔子'/946, l='MpServer', x=-55.94, y=63.00, z=104.31], EntityPig['豬'/818, l='MpServer', x=-175.50, y=66.00, z=48.50], EntitySpider['蜘蛛'/947, l='MpServer', x=-59.50, y=50.00, z=112.50], EntitySheep['綿羊'/819, l='MpServer', x=-162.67, y=68.00, z=58.69], EntitySheep['綿羊'/820, l='MpServer', x=-162.01, y=68.00, z=59.57], EntitySheep['綿羊'/821, l='MpServer', x=-162.53, y=67.00, z=53.88], EntityPig['豬'/822, l='MpServer', x=-168.57, y=66.00, z=50.65], EntitySheep['綿羊'/823, l='MpServer', x=-161.00, y=68.00, z=55.42], EntityZombie['殭屍'/824, l='MpServer', x=-165.21, y=45.00, z=141.51], EntityRabbit['兔子'/825, l='MpServer', x=-160.70, y=70.00, z=132.30], EntityRabbit['兔子'/826, l='MpServer', x=-163.62, y=71.00, z=135.38], EntitySheep['綿羊'/835, l='MpServer', x=-151.68, y=69.00, z=60.23], EntityRabbit['兔子'/836, l='MpServer', x=-156.65, y=70.00, z=129.45], EntitySkeleton['骷髏'/964, l='MpServer', x=-40.50, y=25.00, z=41.50], EntitySkeleton['骷髏'/837, l='MpServer', x=-150.04, y=39.00, z=154.49], EntityZombie['殭屍'/965, l='MpServer', x=-37.50, y=25.00, z=40.50], EntityRabbit['兔子'/838, l='MpServer', x=-145.61, y=73.00, z=144.48], EntityZombie['殭屍'/966, l='MpServer', x=-37.52, y=25.00, z=48.28], EntityRabbit['兔子'/839, l='MpServer', x=-158.24, y=71.00, z=147.34], EntitySkeleton['骷髏'/968, l='MpServer', x=-41.75, y=31.00, z=123.50], EntitySkeleton['骷髏'/969, l='MpServer', x=-44.05, y=32.00, z=122.54], EntityCreeper['苦力怕'/970, l='MpServer', x=-44.78, y=33.00, z=120.50], EntityCreeper['苦力怕'/971, l='MpServer', x=-46.50, y=33.00, z=121.20], EntityRabbit['兔子'/973, l='MpServer', x=-37.53, y=71.00, z=177.11], EntityRabbit['兔子'/974, l='MpServer', x=-38.70, y=71.00, z=179.30], EntityEnderman['終界使者'/849, l='MpServer', x=-132.55, y=49.00, z=129.48], EntityEnderman['終界使者'/850, l='MpServer', x=-139.26, y=49.00, z=136.51], EntityRabbit['兔子'/851, l='MpServer', x=-142.69, y=70.00, z=136.45], EntitySkeleton['骷髏'/852, l='MpServer', x=-135.29, y=60.00, z=148.49], EntityRabbit['兔子'/853, l='MpServer', x=-140.47, y=73.00, z=148.69], EntityRabbit['兔子'/854, l='MpServer', x=-139.35, y=74.00, z=150.42], EntityRabbit['兔子'/855, l='MpServer', x=-141.50, y=75.00, z=149.90], EntityRabbit['兔子'/856, l='MpServer', x=-143.52, y=78.00, z=154.24], EntityRabbit['兔子'/857, l='MpServer', x=-140.65, y=76.50, z=152.17], EntityBat['蝙蝠'/863, l='MpServer', x=-112.49, y=61.10, z=117.25], EntitySkeleton['骷髏'/864, l='MpServer', x=-116.35, y=49.00, z=112.80], EntityEnderman['終界使者'/865, l='MpServer', x=-116.62, y=48.00, z=114.64], EntitySkeleton['骷髏'/866, l='MpServer', x=-116.18, y=48.00, z=118.44], EntityBat['蝙蝠'/867, l='MpServer', x=-112.25, y=65.10, z=116.55], EntitySkeleton['骷髏'/868, l='MpServer', x=-112.50, y=21.00, z=129.50], EntitySkeleton['骷髏'/869, l='MpServer', x=-115.45, y=46.00, z=128.22], EntityCreeper['苦力怕'/870, l='MpServer', x=-114.65, y=40.00, z=171.50], EntityChicken['雞'/880, l='MpServer', x=-98.52, y=63.00, z=52.17], EntityChicken['雞'/881, l='MpServer', x=-97.09, y=63.00, z=53.70], EntityItem['item.item.egg'/882, l='MpServer', x=-100.66, y=63.00, z=50.73], EntityChicken['雞'/883, l='MpServer', x=-105.35, y=64.00, z=49.08], EntityChicken['雞'/884, l='MpServer', x=-105.16, y=64.00, z=49.69], EntityBat['蝙蝠'/885, l='MpServer', x=-98.75, y=52.10, z=108.63], EntitySkeleton['骷髏'/886, l='MpServer', x=-100.79, y=51.00, z=108.51], EntityBat['蝙蝠'/887, l='MpServer', x=-105.56, y=50.03, z=110.63], EntitySkeleton['骷髏'/888, l='MpServer', x=-111.81, y=47.00, z=119.28], EntityBat['蝙蝠'/889, l='MpServer', x=-101.75, y=51.10, z=116.25], EntityEnderman['終界使者'/890, l='MpServer', x=-98.50, y=51.00, z=123.73], EntityCreeper['苦力怕'/891, l='MpServer', x=-98.19, y=51.00, z=125.49], EntityCreeper['苦力怕'/892, l='MpServer', x=-101.40, y=51.00, z=122.83], EntityCreeper['苦力怕'/893, l='MpServer', x=-111.46, y=49.00, z=113.89], EntityCreeper['苦力怕'/894, l='MpServer', x=-108.69, y=43.00, z=170.97], EntityCreeper['苦力怕'/895, l='MpServer', x=-107.48, y=44.00, z=166.79]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:529)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161895632 bytes (154 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_E7 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{2.1.3.220} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.220-universal.jar) 
	UCHIJAAAAAAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAAAAAAA	bamboomod{Minecraft1.10.2 var3.0.0.12.2} [bamboomod] (Bamboo-3.0.0.12.2.jar) 
	UCHIJAAAAAAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAAAAAAA	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAAAAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAAAAAAA	harvestfestival{0.6.0-219} [Harvest Festival] (Harvest-Festival-1.10.2-0.6.0-219.jar) 
	UCHIJAAAAAAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAAAAAAA	JEI{3.14.8.422} [Just Enough Items] (jei_1.10.2-3.14.8.422.jar) 
	UCHIJAAAAAAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAAAAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAAAAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal-tw.jar) 
	UCHIJAAAAAAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.10.2.jar) 
	UCHIJAAAAAAAAA	Waila{1.7.0} [Waila] (Waila-1.10.2.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  codechicken.nei.asm.NEITransformer
HFTransformer (Harvest-Festival-1.10.2-0.6.0-219.jar)
  joshie.harvest.asm.HFTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TachibanaTex3D[BambooMod][ver1.0], TachibanaTex3D[ver2.2]
	Current Language: 繁體中文 (台灣)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E7
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.36
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by NONO219** [comment]
老哥你通俗地说说你的问题吧

**Comment by luke82304** [comment]
> 老哥你通俗地說說你的問題吧

最後建造市政廳的時候 只要拿出藍圖就會崩潰了
試過了最新的幾個版本 還是都會自動關掉

**Comment by luke82304** [comment]
> 老哥你通俗地說說你的問題吧

之前跟鐵匠對話時 也會崩潰 把版本219換成218 就解決了
但這次就不行了 苦惱了很久

**Comment by NONO219** [comment]
你是不是在已經建立了一個存檔之後才安裝的mod，或者說是已經建立了一個帶有舊版本的mod的存檔后更新了這個mod？我之前就是因為在一個安裝了0.5.x版本的HF mod的存檔更換了最新版本的HF后就開始‘蹦蹦蹦咖喱給給’了。

目前來看0.5.x的版本是最穩定的，但是就是沒有節日什麼的，單純種田和npc商店與對話系統，而且點右鍵打開菜單就會崩崩崩。比較無聊。相比之下0.6.x的版本就各種蜜汁崩盤。

附加一個，用carryon mod搬運這個harvestfestival的物品會發生崩潰。

**解決**：去下載個discord，加入這個的mod的群組，裡面有個長期在線的負責人，你有什麼問題就@他并發送你的crashreport，他會幫你解答的蛤。

**Comment by luke82304** [comment]
> 你是不是在已經建立了一個存檔之後才安裝的MOD，或者說是已經建立了一個帶有舊版本的國防部的存檔後更新了這個MOD？我之前就是因為在一個安裝了0.5.x版本的HF國防部的存檔更換了最新版本的HF後就開始'蹦蹦蹦咖哩給給'了。
> 
> 目前來看0.5.x的版本是最穩定的，但是就是沒有節日什麼的，單純種田和NPC商店與對話系統，而且點右鍵打開菜單就會崩崩崩。比較無聊。相比之下0.6.x的版本就各種蜜汁崩盤。
> 
> 附加一個，用carryon mod搬運這個harvestfestival的物品會發生崩潰。
> 
> **解決**：去下載個不和諧，加入這個的MOD的群組，裡面有個長期在線的負責人，你有什麼問題就@他並發送你的crashreport，他會幫你解答的蛤。

好的謝謝您
