### ISSUE TITLE
Client code trying to run server side

### ISSUE THREAD

**Issue by LemADEC** [joshiejack/Harvest-Moon#31]
Using notably
Harvest-Festival-1.10.2-0.5.2.jar
forge-1.10.2-12.18.1.2092-universal.jar
spongeforge-1.10.2-2092-5.0.0-BETA-1752.jar

When trying to place the carpenter building, errors are reported on console when operation is failed:

```
[12:43:02] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
>       at joshie.harvest.core.helpers.ChatHelper.displayChatMessages(ChatHelper.java:17) ~[ChatHelper.class:?]
>       at joshie.harvest.core.helpers.ChatHelper.displayChat(ChatHelper.java:55) ~[ChatHelper.class:?]
>       at joshie.harvest.buildings.item.ItemBlueprint.func_77659_a(ItemBlueprint.java:78) ~[ItemBlueprint.class:?]
>       at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:122) ~[PacketUtil.class:1.10.2-2092-5.0.0-BETA-1752]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
>       at joshie.harvest.core.helpers.ChatHelper.displayChatMessages(ChatHelper.java:17) ~[ChatHelper.class:?]
>       at joshie.harvest.core.helpers.ChatHelper.displayChat(ChatHelper.java:55) ~[ChatHelper.class:?]
>       at joshie.harvest.buildings.item.ItemBlueprint.func_77659_a(ItemBlueprint.java:78) ~[ItemBlueprint.class:?]
>       at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:122) ~[PacketUtil.class:1.10.2-2092-5.0.0-BETA-1752]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 5 more
```

and

```
[12:46:40] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
>       at joshie.harvest.core.helpers.ChatHelper.displayChatMessages(ChatHelper.java:17) ~[ChatHelper.class:?]
>       at joshie.harvest.core.helpers.ChatHelper.displayChat(ChatHelper.java:55) ~[ChatHelper.class:?]
>       at joshie.harvest.buildings.item.ItemBlueprint.func_77659_a(ItemBlueprint.java:81) ~[ItemBlueprint.class:?]
>       at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:122) ~[PacketUtil.class:1.10.2-2092-5.0.0-BETA-1752]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 5 more
```

**Comment by joshiejack** [comment]
_I do wonder about myself sometimes._
