### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by tobi1449** [joshiejack/Harvest-Moon#57]
We're currently experiencing this crash when trying to start our small modded server:

```
java.lang.NullPointerException: Ticking entity
    at joshie.harvest.crops.CropHelper.getCropDataAt(CropHelper.java:85)
    at joshie.harvest.crops.block.BlockHFCrops.feedAnimal(BlockHFCrops.java:390)
    at joshie.harvest.animals.entity.EntityAIEat.func_75246_d(EntityAIEat.java:42)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
```

The full crashlog is [here](https://gist.github.com/tobi1449/349713e7457497e177c9ce150d3084a6).

**Comment by tobi1449** [comment]
Ok, the crash is not instantly on startup, but occurs after the server has been running for a few minutes.

**Comment by joshiejack** [comment]
It will be related to cows/sheep trying to eat crops. Ideally keep animals a bit away from crops until I can fix it. To prevent the crash. Although something weird is going on with it, for it to null there.

**Comment by tobi1449** [comment]
This crash is definitly related to #58 
The server instantly crashes, as soon as the dirt block comes into view.

**Comment by joshiejack** [comment]
Okay I rewrote a bit of it. So HOPEFULLY it should no longer nullpointer. Since it's a server, I'm not sure how feasible this request is but could you possibly try it out this build (when it's done). And see if fixes the issue? (Worst case the crop should be like dead busy). Well that's if you haven't fixed the issue :p. Kind of a hard one to recreate it heh.

http://joshiejack.uk:8080/job/Harvest-Festival/job/1.10.2/89/

**Comment by tobi1449** [comment]
Looks like it works, thank you :+1:
