### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by tobi1449** [joshiejack/Harvest-Moon#58]
On our server an Enderman managed to place a vanilla grass block on top of a full grown Harvest Festival Grass crop. Whenever a player put that grass block in his crosshairs, the client crashed:
`
java.lang.NullPointerException: Unexpected error
    at joshie.harvest.crops.CropHelper.getCropBoundingBox(CropHelper.java:48)
    at joshie.harvest.crops.block.BlockHFCrops.func_185496_a(BlockHFCrops.java:265)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
    at net.minecraft.block.Block.func_180636_a(Block.java:603)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:448)
    at net.minecraft.world.World.func_147447_a(World.java:1018)
    at net.minecraft.entity.Entity.func_174822_a(Entity.java:1451)
    at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:343)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1211)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)`

The full crash log is [here](https://gist.github.com/tobi1449/aaa566f23d8cb10cbc9216627f6c132a)

The crash persisted even when a player broke the grass crop underneath it.
This crash might be related to #57

**Comment by joshiejack** [comment]
Ahhhh! Damn enderman breaking things. D=
