### ISSUE TITLE
Console spamming Network exception

### ISSUE THREAD

**Issue by LemADEC** [joshiejack/Harvest-Moon#62]
About 10 mn after a player got kicked (not whitelisted), with nobody else online, console started spamming an exception about network:

```
[19:26:48] [Server thread/INFO]: Stucuk lost connection: You are not white-listed on this server!
[19:26:48] [Server thread/INFO]: Stucuk left the game
[19:36:11] [Server thread/INFO]: [Server] **SERVER IS SAVING THE MAP**
[19:36:11] [Server thread/INFO]: Saving...
[19:36:11] [Server thread/INFO]: Saved the world
[19:36:11] [Server thread/INFO]: [Server] **MAP SAVE IS COMPLETE**
[19:38:29] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.NullPointerException
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:132) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:293) ~[FMLOutboundHandler.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[MessageToMessageEncoder.class:?]
>       at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
>       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:249) [SimpleNetworkWrapper.class:?]
>       at joshie.harvest.core.network.PenguinNetwork.sendToClient(PenguinNetwork.java:25) [PenguinNetwork.class:?]
>       at joshie.harvest.core.network.PacketHandler.sendToClient(PacketHandler.java:24) [PacketHandler.class:?]
>       at joshie.harvest.player.quests.QuestDataServer.syncQuest(QuestDataServer.java:75) [QuestDataServer.class:?]
>       at joshie.harvest.player.quests.QuestDataServer.sync(QuestDataServer.java:59) [QuestDataServer.class:?]
>       at joshie.harvest.player.PlayerTrackerServer.syncPlayerStats(PlayerTrackerServer.java:90) [PlayerTrackerServer.class:?]
>       at joshie.harvest.player.PlayerTrackerServer.newDay(PlayerTrackerServer.java:80) [PlayerTrackerServer.class:?]
>       at joshie.harvest.core.handlers.EventsHandler.onTick(EventsHandler.java:48) [EventsHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_217_EventsHandler_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130) [EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99) [EventBus.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) [FMLCommonHandler.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[19:38:29] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:132) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
>       at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:293) ~[FMLOutboundHandler.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) ~[MessageToMessageEncoder.class:?]
>       at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
>       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:249) [SimpleNetworkWrapper.class:?]
>       at joshie.harvest.core.network.PenguinNetwork.sendToClient(PenguinNetwork.java:25) [PenguinNetwork.class:?]
>       at joshie.harvest.core.network.PacketHandler.sendToClient(PacketHandler.java:24) [PacketHandler.class:?]
>       at joshie.harvest.player.quests.QuestDataServer.syncQuest(QuestDataServer.java:75) [QuestDataServer.class:?]
>       at joshie.harvest.player.quests.QuestDataServer.sync(QuestDataServer.java:59) [QuestDataServer.class:?]
>       at joshie.harvest.player.PlayerTrackerServer.syncPlayerStats(PlayerTrackerServer.java:90) [PlayerTrackerServer.class:?]
>       at joshie.harvest.player.PlayerTrackerServer.newDay(PlayerTrackerServer.java:80) [PlayerTrackerServer.class:?]
>       at joshie.harvest.core.handlers.EventsHandler.onTick(EventsHandler.java:48) [EventsHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_217_EventsHandler_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130) [EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99) [EventBus.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) [FMLCommonHandler.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

This happens more than 50 times during the same tick until the game kill the report.
This sequence happened twice.

We're using:
forge-1.10.2-12.18.1.2094-universal.jar
Harvest-Festival-1.10.2-0.5.3.jar

**Comment by GirafiStudios** [comment]
Do you have any other mods than HF ? :)

**Comment by joshiejack** [comment]
Sorry that I've not got around to this yet. I'll take a look tomorrow.

**Comment by joshiejack** [comment]
Ok can you try this one when it's done and let me know. http://joshiejack.uk:8080/job/Harvest-Festival/job/1.10.2/91/

**Comment by joshiejack** [comment]
Going to close this as there has been no response. Going to assume fixed.
