### ISSUE TITLE
Growing beetroot is crashy

### ISSUE THREAD

**Issue by purpleposeidon** [joshiejack/Harvest-Moon#79]
java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 4 on block minecraft:beetroots, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222)
    at net.minecraft.block.BlockCrops.func_185528_e(BlockCrops.java:62)
    at net.minecraft.block.BlockCrops.func_176203_a(BlockCrops.java:252)
    at joshie.harvest.crops.handlers.state.StateHandlerSeedFood.getState(StateHandlerSeedFood.java:16)
    at joshie.harvest.crops.block.BlockHFCrops.func_176221_a(BlockHFCrops.java:295)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:410)
    at net.minecraft.client.gui.GuiOverlayDebug.func_175238_c(GuiOverlayDebug.java:207)
    at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.getRight(GuiIngameForge.java:913)
    at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.access$200(GuiIngameForge.java:895)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:689)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by joshiejack** [comment]
And this is which version because i fixed it a while ago...

**Comment by purpleposeidon** [comment]
0.5.6

**Comment by joshiejack** [comment]
Yea it was fixed in 0.5.7
