### ISSUE TITLE
Harvest Festival Crash Report

### ISSUE THREAD

**Issue by jlisa** [joshiejack/Harvest-Moon#88]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HFTransformer (Harvest-Festival-1.10.2-0.5.11.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/19/16 6:44 PM
Description: Exception ticking world

java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
    at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
    at net.minecraftforge.common.ForgeHooks.getGrassSeed(ForgeHooks.java:145)
    at net.minecraft.block.BlockTallGrass.getDrops(BlockTallGrass.java:200)
    at net.minecraft.block.Block.func_180653_a(Block.java:544)
    at net.minecraft.block.Block.func_176226_b(Block.java:537)
    at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:65)
    at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:58)
    at net.minecraft.block.Block.func_180645_a(Block.java:480)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
    at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
    at net.minecraftforge.common.ForgeHooks.getGrassSeed(ForgeHooks.java:145)
    at net.minecraft.block.BlockTallGrass.getDrops(BlockTallGrass.java:200)
    at net.minecraft.block.Block.func_180653_a(Block.java:544)
    at net.minecraft.block.Block.func_176226_b(Block.java:537)
    at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:65)
    at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:58)
    at net.minecraft.block.Block.func_180645_a(Block.java:480)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)

-- Affected level --
Details:
    Level name: Copy of New World
    All players: 1 total; [EntityPlayerMP['PrincessAlex8'/339, l='Copy of New World', x=-143.05, y=65.02, z=198.62]]
    Chunk stats: ServerChunkCache: 447 Drop: 0
    Level seed: 5101760483169192932
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (0,64,256), Chunk: (at 0,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 10208 game time, 10208 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_111, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 136639864 bytes (130 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.2.2107 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2107.jar) 
    UCHIJAAAA   Forge{12.18.2.2107} [Minecraft Forge](forge-1.10.2-12.18.2.2107.jar) 
    UCHIJAAAA   harvestfestival{0.5.11} [Harvest Festival](Harvest-Festival-1.10.2-0.5.11.jar) 
    Loaded coremods (and transformers): 
HFTransformer (Harvest-Festival-1.10.2-0.5.11.jar)
  joshie.harvest.asm.HFTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['PrincessAlex8'/339, l='Copy of New World', x=-143.05, y=65.02, z=198.62]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by joshiejack** [comment]
Disable the config that disables the vanilla seeds from dropping for now to fix this. Will fix it myself asap.
